[package]
name = "kq"
version = "0.0.0"
authors = ["JMA"]
description = "Low-level kqueue interface for BSDs"
license = "MIT"
readme = "README.md"
edition = "2024"

[dependencies]
bitflags = "^1"
libc = "^0"
